Use headless notebooks for training
substratusai/models pull request #12
Opened 2023-06-15 12:22 UTC by nstogner

This allows us to view the output of a training job and visualize loss graphs, etc that the notebook can produce while training.

2023-06-15 12:24 UTC, nstogner commented
NOTE: Github can render `.ipynb` files: https://github.com/substratusai/models/blob/headless-notebook-training/facebook-opt-125m/train.ipynb

2023-06-18 17:49 UTC, samos123 approved these changes

2023-06-18 18:03 UTC, samos123 commented on facebook-opt-125m/scripts/build.sh
> +jupyter nbconvert --debug --to notebook --execute /model/src/build.ipynb --output /model/logs/build.ipynb
shoudln't this be --to python instead of --to notebook?

2023-06-18 18:05 UTC, samos123 commented on facebook-opt-125m/scripts/build.sh
> +jupyter nbconvert --debug --to notebook --execute /model/src/build.ipynb --output /model/logs/build.ipynb
ignore I see this is a way of executing the notebook: https://nbconvert.readthedocs.io/en/latest/usage.html#convert-notebook

2023-06-18 18:25 UTC, samos123 requested changes

2023-06-18 18:25 UTC, samos123 commented on facebook-opt-125m/README.md
> +docker run -it -p 8080:8080 facebook-opt-125m ./serve.sh
isn't  serve.sh under /model/scripts in your case? so shouldn't it be `./scripts/serve.sh` or just plain `serve.sh`

2023-06-18 18:25 UTC, samos123 commented on facebook-opt-125m/README.md
> +docker run -it -p 8888:8888 facebook-opt-125m ./dev.sh
I think this path is incorrect

2023-06-18 19:55 UTC, samos123 commented
curious, how do you get the ipynb files out from the container after running dev.sh? The use case would be to work on the train.ipynb, get it to work, download train.ipynb from container to local directory, git add train.ipynb.

My naive way would be to call `docker cp` to get the `train.ipynb` file out from container into local dir.

2023-06-18 21:38 UTC, samos123 commented on facebook-opt-125m/README.md
> +docker run -it -p 8888:8888 facebook-opt-125m ./dev.sh
I just tested this and seems it's incorrect at least based on me trying out falcon-7b-instruct. It should be `dev.sh` or `./scripts/dev.sh`

2023-06-18 22:13 UTC, nstogner commented on facebook-opt-125m/README.md
> +docker run -it -p 8080:8080 facebook-opt-125m ./serve.sh
Good catch, it should be ‘serve.sh’

2023-06-18 22:28 UTC, nstogner commented on facebook-opt-125m/README.md
> +docker run -it -p 8888:8888 facebook-opt-125m ./dev.sh
Agreed, solved

2023-06-18 22:29 UTC, nstogner commented
Updated the README. You can now develop with the notebook b/c the docker container mounts `./src` in the README steps.

2023-06-18 22:40 UTC, samos123 approved these changes

2023-06-18 23:47 UTC, merged