use basaran for serving for falcon-7b-instruct
substratusai/models pull request #7
Opened 2023-06-09 08:07 UTC by samos123

Basaran provides both streaming UI to show tokens as they are being generated and also provides an OpenAI compatible endpoint.

2023-06-09 13:36 UTC, nstogner commented
Looks like basaran uses SSE (server sent events): https://github.com/hyperonym/basaran/blob/0c4b8a597548e3f6242129999bd4114085541c06/basaran/__main__.py#L212

2023-06-09 13:40 UTC, nstogner commented on falcon-7b-instruct/requirements.txt
> +basaran
Basaran also comes with additional endpoints that dont make a ton of sense with our arch... https://github.com/hyperonym/basaran/blob/0c4b8a597548e3f6242129999bd4114085541c06/basaran/__main__.py#L113

Perhaps we dont worry about this... but just wanted to point it out.

2023-06-09 13:52 UTC, nstogner commented on falcon-7b-instruct/Dockerfile
> +CMD PORT=8080 python -m basaran
I lean towards the model contract being:

`serve.sh` & `train.sh`

2023-06-09 13:54 UTC, nstogner commented on falcon-7b-instruct/Dockerfile
> +CMD PORT=8080 python -m basaran
Perhaps those are the defaults, and the Model object allows for over-riding them.

2023-06-09 15:44 UTC, samos123 commented on falcon-7b-instruct/Dockerfile
> +CMD PORT=8080 python -m basaran
+1 to having serve.sh and train.sh. I'm not so sure for the use case of infer.sh? Does that need to be a contract?

2023-06-09 19:33 UTC, nstogner requested changes

2023-06-09 19:33 UTC, nstogner commented on falcon-7b-instruct/serve.sh
> +
I think `set -e` is needed.

2023-06-09 19:34 UTC, samos123 commented on falcon-7b-instruct/serve.sh
> +
fail if something goes wrong is a good idea. Will add.

2023-06-09 19:34 UTC, samos123 commented on falcon-7b-instruct/serve.sh
> +
are you ok with setting `set -xe`?

2023-06-09 19:36 UTC, samos123 commented on falcon-7b-instruct/serve.sh
> +
done

2023-06-10 06:36 UTC, samos123 commented
merging since change requested was done and want to test it out in substratus end to end

2023-06-10 06:36 UTC, merged